server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/userdb?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    locations: classpath:db/migration, classpath:db/testdb
    
mcsv:
  qualification:
    url: "http://QUALIFIER-SERVICE/api/qualifications/users/"
  hotel:
    url: "http://HOTEL-SERVICE/api/hotels/"

logging:
  level:
    com.joelmaciel.user_service: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO


